version: "3.8"

services:
  db:
    container_name: database
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
      - botnet
    volumes:
      - pgdata:/var/lib/postgresql/data
  tgbot:
    container_name: bot
    build:
      context: .
    command: python app.py
    networks:
      - botnet
    env_file:
      - ".env"
    # Бот стартует после запуска базы
    depends_on:
      - db
      - django
  django:
    container_name: djangoproject
    build:
      context: .
    command: python django_app.py runserver 0.0.0.0:8000 --noreload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - botnet
    env_file:
      - ".env"
    depends_on:
      - db
volumes:
  pgdata:

networks:
  botnet:
    # указывается драйвер сети
    driver: bridge