# Generated by Django 3.1.4 on 2020-12-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('user_manager', '0001_initial'),
	]
	
	operations = [
		migrations.RemoveField(
				model_name = 'user',
				name = 'email',
		),
		migrations.AlterField(
				model_name = 'purchase',
				name = 'shipping_address',
				field = models.CharField(max_length = 255, null = True, verbose_name = 'Адрес Доставки'),
		),
	]
