# Generated by Django 3.1.4 on 2020-12-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('user_manager', '0002_auto_20201212_1752'),
	]
	
	operations = [
		migrations.RenameField(
				model_name = 'purchase',
				old_name = 'product_id',
				new_name = 'product',
		),
		migrations.AlterField(
				model_name = 'purchase',
				name = 'id',
				field = models.CharField(max_length = 30, primary_key = True, serialize = False),
		),
	]
