# Generated by Django 3.1.4 on 2020-12-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0004_auto_20201212_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
    ]
